# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jackie
tagline:          'Android Developer'
description:      '一份耕耘一份收获,多份分享多份快乐;
                  分享有用的文档,开发自己喜欢的应用'
url:              http://jackie880823.github.io
baseurl:          ""
root:             /

# About/contact
author:
  name:           'Jackie Blog'
  url:            http://jackie880823.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jackie880823
