# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jackie
tagline:          'Android Developer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://jackie880823.github.io
baseurl:          http://jackie880823.github.io

# About/contact
author:
  name:           'Jackie Blog'
  url:            http://jackie880823.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jackie880823
