# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:               Jackie
tagline:             Android Developer
description:         ''
url:                 http://jackie880823.github.io
baseurl:             ''

# About/contact
author:
  name:              Jackie Blog
  url:               http://jackie880823.github.io
  email:             jackie880823@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jackie880823
