# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jackie Blog
tagline:             Android
description:         ''
url:                 http://jackie880823.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jackie Blog
  url:               http://jackie880823.github.io/
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
